spring:
 datasource:
  url: jdbc:mysql://192.168.64.128:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: toor
  driver-class-name: com.mysql.jdbc.Driver
service:
 port: 8080
 context-path: /springboot
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
 config: classpath:log4j.yaml